version: '3'
services:
  fhem:
    image: fhem/fhem:latest
    restart: always
    privileged: true
    user: root
    ports:
      - "8082:8083"
    volumes:
      - ./fhem:/opt/fhem
  ngrok:
    image: wernight/ngrok:${NGROK_DOCKER_IMAGE_TAG:-armhf}
    user: root
    command: /bin/sh -c "ngrok authtoken $NGROK_AUTH && ngrok start fhem grafana"
    volumes:
      - ./ngrok.yml:/root/.ngrok2/ngrok.yml
    environment:
      NGROK_AUTH: "${NGROK_AUTH}"
  influxdb:
    image: influxdb:latest
    user: root
    ports:
      - "8083:8083"
      - "8086:8086"
      - "8090:8090"
    environment:
      INFLUXDB_DB: 'fhem'
      INFLUXDB_ADMIN_USER: 'fhemadmin'
      INFLUXDB_ADMIN_USER_PASSWORD: 'fhemadmin'
      INFLUXDB_USER: 'fhem'
      INFLUXDB_USER_PASSWORD: 'fhem'
    volumes:
      - influxdb_data:/var/lib/influxdb
  grafana:
    image: grafana/grafana:latest
    user: root
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,briangann-gauge-panel,natel-plotly-panel,grafana-simple-json-datasource'
    links:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana
volumes:
  influxdb_data:
  grafana_data: